server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: false
    fectch-registry: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/

