server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fectch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:7002/eureka/

